### ISSUE TITLE
allow per-site broken devices in Gluon

### ISSUE THREAD

**Issue by blocktrron** [freifunk-darmstadt/projects#11]
Aktuell haben wir einen manuellen patch, welcher das BROKEn flag des NWA55AXE für uns entfernt.

Dies sollte durch eine upstream-Lösung welce bspw. das BROKEN flag aus der Site überschreiben kann.

**Comment by herbetom** [comment]
Durch @blocktrron in https://github.com/freifunk-gluon/gluon/pull/3054 implementiert :tada:
